name: Update Data and Deploy to Database
on: workflow_dispatch
jobs:
  Clean-Cache:
    runs-on: ubuntu-latest
    steps:
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@12.1
        with:
          lein: 2.9.8                  # Leiningen
      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
          # List all files containing dependencies:
          # key: cljdeps-${{ hashFiles('deps.edn') }}
          key: cljdeps-${{ hashFiles('project.clj') }}

      - name: Get leiningen version
        run: lein -v

      - name: Clean Cache
        run: rm  -r output/cache

      - name: Run Scrapper
        run: lein classes-by-college

      - name: Pushes to Repository with 
        uses: tech-thinker/push-to-repo@main
        env:
            API_TOKEN_GITHUB: ${{ secrets.GIT_PAT_TOKEN }}
        with:
            user-name: "github-actions[bot]"
            user-email: github-actions[bot]@users.noreply.github.com
            source-directory: "output/by_college"
            destination-github-username: "KFU-reg"
            destination-repository-name: "database"
            target-branch: master
